<p style="font-family: Arial; font-size:3em;color:black;"> Lab Exercise 3 </p>

# 1

In [19]:
import numpy as np
from numpy.linalg import inv
from numpy.linalg import det

a_mat = np.array([[5,2,3],[6,1,3],[2,4,1]])
b_mat = a_mat[:2, :2]
c_mat = a_mat[1:, 1:]

print("Matrix A is:\n",a_mat)
print("Matrix B is:\n",b_mat)
print("Matrix C is:\n",c_mat)

Matrix A is:
 [[5 2 3]
 [6 1 3]
 [2 4 1]]
Matrix B is:
 [[5 2]
 [6 1]]
Matrix C is:
 [[1 3]
 [4 1]]


# 2 and 3

In [25]:
d_mat = np.array([[4,-7,4],[5,6,-1],[-4,2,5]])
print("Matrix D is:\n",d_mat)

print("AD:\n", np.matmul(a_mat, d_mat))
print("DA:\n", np.matmul(d_mat, a_mat))
print("\nTherefore, the calculation for matrix AD and DA are not equal")

Matrix D is:
 [[ 4 -7  4]
 [ 5  6 -1]
 [-4  2  5]]
AD:
 [[ 18 -17  33]
 [ 17 -30  38]
 [ 24  12   9]]
DA:
 [[-14  17  -5]
 [ 59  12  32]
 [  2  14  -1]]

Therefore, the calculation for matrix AD and DA are not equal


# 4

In [47]:
# Manual Calculations:
a,b = b_mat[0,0], b_mat[0,1]
c,d = b_mat[1,0], b_mat[1,1]

inv_coeff = 1/(a*d -b*c)
inv_mat = np.array([[d,-b],[-c, a]])

manual_det_b = a*d - c*b 
manual_inv_b = inv_coeff*inv_mat




print("The manually calculated determinant of matrix B yielded: ",manual_det_b)
print("Numpy matrix B determinant: ", det(b_mat))

print("\nThe manually calculated inverse of matrix B:\n", manual_inv_b)
print("The Numpy inverse of Matrix B: \n", inv(b_mat))

print("\nFrom these results we can see that the manual calculations are identical and agree with the NumPy results")



The manually calculated determinant of matrix B yielded:  -7
Numpy matrix B determinant:  -6.999999999999999

The manually calculated inverse of matrix B:
 [[-0.14285714  0.28571429]
 [ 0.85714286 -0.71428571]]
The Numpy inverse of Matrix B: 
 [[-0.14285714  0.28571429]
 [ 0.85714286 -0.71428571]]

From these results we can see that the manual calculations are identical and agree with the NumPy results


# 5

In [54]:
inv_d_mat = inv(d_mat)

print("(D)(D^-1):\n", np.round(np.matmul(d_mat, inv_d_mat)))

print("\n(D^-1)(D):\n", np.round(np.matmul(inv_d_mat, d_mat)))

print("\nBoth Matrices are identity matrices which have a diagonal of 1 with the rest of the elements being 0.")

(D)(D^-1):
 [[ 1.  0.  0.]
 [ 0.  1. -0.]
 [-0. -0.  1.]]

(D^-1)(D):
 [[ 1.  0.  0.]
 [ 0.  1. -0.]
 [ 0.  0.  1.]]

Both Matrices are identity matrices which have a diagonal of 1 with the rest of the elements being 0.
