<p style="font-family: Arial; font-size:3em;color:black;"> Lab 1 </p>

Students name in this Group:  Syed Hamza Ali

In [2]:
# importing numpy
import numpy as np

In [3]:
# Create a numpy array with the elements "1, 2, 3, 5, 0", print the array and test if all of its elements are non-zero.
a = np.array([1,2,3,5,0])
print("The numpy array a is: ", a)

# np.all checks if all elements in boolean array are true, therefore will return true if no non-zero elements exist
# np.logical_not flips the bool value 
# (a == 0) if non zero exists will return false, otherwise true 

# creating a function to check for non zero elements to reduce redundancy
def zero_check(input_array):

    test = np.all(np.logical_not(input_array == 0))
    
    if test:
        print('All elements in the array are non zero')
    else:
        print('The array has elements that are zero')

zero_check(a)

The numpy array a is:  [1 2 3 5 0]
The array has elements that are zero


In [4]:
# Create a numpy array with the elements "3, -1, 3, 7, 2", print the array and test if any of its elements is non-zero.
b = np.array([3,-1,3,7,2])
print("The numpy array b is: ", b)
zero_check(b)

The numpy array b is:  [ 3 -1  3  7  2]
All elements in the array are non zero


In [5]:
# Create a numpy array with the elements "0, 0, 0, 0", print the array and test if any of its elements is non-zero.
c = np.array([0,0,0,0])
print("The numpy array c is: ", c)
zero_check(c)

The numpy array c is:  [0 0 0 0]
The array has elements that are zero


In [6]:
# Create a numpy array with the elements "56, -2, 7", print the array and the amount of memory required to store it.
d = np.array([56, -2, 7])
print("The numpy array d is: ", d, ", its memory size is: ", d.itemsize*d.size, "bits")

The numpy array d is:  [56 -2  7] , its memory size is:  12 bits


In [7]:
# Create a numpy array with 10 zeros and print the array.
z = np.zeros(10)
# Create a numpy array with 6 ones and print the array.
o = np.ones(6)
# Create a numpy array with 12 '3's and print the array. [3 3 3 3 3 3 3 3 3 3 3 3]
t = np.ones(12)*3
print(z)
print(o)
print(t)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1.]
[3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]


In [8]:
# Create a numpy array of the integers from 8 to 20 and print the array. (make sure 20 itself is included) hint:  use "arange" method
arr_1 = np.arange(8, 21)
print('Array of Integers between 8 and 20: ', arr_1)
# Create a numpy array of the even integers from 8 to 20 and print the array. (make sure 20 itself is included)   hint:  use "arange" method
arr_2 = np.arange(8, 21, 2)
print('Array of Even Integers between 8 and 20: ', arr_2)

Array of Integers between 8 and 20:  [ 8  9 10 11 12 13 14 15 16 17 18 19 20]
Array of Even Integers between 8 and 20:  [ 8 10 12 14 16 18 20]


In [9]:
# Create a numpy array consisting of 100 random elements from normal distribution with mean of 2 and std of 0.5. Print the mean, max, min and std of the array.
ra1 = np.random.normal(2, 0.5, 100)
print("Random Array 1 (100 elements) has mean:", ra1.mean(), ", max:", ra1.max(),", min:", ra1.min(),", std:", ra1.std(),".")
# Create a numpy array consisting of 1000 random elements from normal distribution with mean of 2 and std of 0.5. Print the mean, max, min and std of the array.
ra2 = np.random.normal(2, 0.5, 1000)
print("Random Array 2 (1000 elements) has mean:", ra2.mean(), ", max:", ra2.max(),", min:", ra2.min(),", std:", ra2.std(),".")
# Create a numpy array consisting of 1000000 random elements from normal distribution with mean of 2 and std of 0.5. Print the mean, max, min and std of the array.
ra3 = np.random.normal(2, 0.5, 1000000)
print("Random Array 3 (1000000 elements) has mean:", ra3.mean(), ", max:", ra3.max(),", min:", ra3.min(),", std:", ra3.std(),".")
# (Bonus question) Looking at the three above examples with 1000, 5000, and 10000 random elements, do you have any observations about mean and std values?
print("Looking at the three examples we observe that the accuracy of the mean and std are slightly greater by being a few decimals closer to 0.5 and 2.")
print("The greater the amount of elements, the more accurate mean and std become.") 

Random Array 1 (100 elements) has mean: 2.0617301791327485 , max: 3.0866891953128084 , min: 0.7120181035214548 , std: 0.4257986733365209 .
Random Array 2 (1000 elements) has mean: 1.9866069212125326 , max: 3.488252409235086 , min: 0.306335454200636 , std: 0.48457186129305657 .
Random Array 3 (1000000 elements) has mean: 2.0003341136139094 , max: 4.871278815503993 , min: -0.358464927859548 , std: 0.4995807916746338 .
Looking at the three examples we observe that the accuracy of the mean and std are slightly greater by being a few decimals closer to 0.5 and 2.
The greater the amount of elements, the more accurate mean and std become.
