## <p style="font-family: Arial; font-size:3em;color:black;"> Lab Exercise 4 </p>

# Group 10
Team members:
- Poleo Vargas, Ricardo
- Naji, Mohamed Oussama
- Ali, Syed Hamza
- Jayswal, Ishabahen Dilipkumar
- Karande, Pranali
- Tran, Cong Le Anh Tu

# Installations and imports

## Installations

## Imports

# Task 1: Calculate the bag of words (without TF-IDF, just word counts) matrix for the following 5 phrases.
- college student
- airport taxi driver
- Toronto art museum
- life art
- machine learning student

In [1]:
import numpy as np

# Define the list of phrases
phrases = [
    "college student",
    "airport taxi driver",
    "Toronto art museum",
    "life art",
    "machine learning student"
]
print(f'phrases: {phrases}')

words = [phrase.split() for phrase in phrases]
print(f'words: {words}')

vocabulary = sorted(list(set([word for phrase in words for word in phrase])))
print(f'vocabulary: {vocabulary}')

bag_of_words_matrix = np.zeros((len(phrases), len(vocabulary)), dtype=int)
print('bag_of_words_matrix (init): ')
print(bag_of_words_matrix)

# Count word occurrences and fill the matrix
for i, phrase in enumerate(phrases):
    for word in phrase.split():
        word_index = vocabulary.index(word)
        bag_of_words_matrix[i, word_index] += 1

# Print the bag of words matrix
print('bag_of_words_matrix (final): ')
print(bag_of_words_matrix)


phrases: ['college student', 'airport taxi driver', 'Toronto art museum', 'life art', 'machine learning student']
words: [['college', 'student'], ['airport', 'taxi', 'driver'], ['Toronto', 'art', 'museum'], ['life', 'art'], ['machine', 'learning', 'student']]
vocabulary: ['Toronto', 'airport', 'art', 'college', 'driver', 'learning', 'life', 'machine', 'museum', 'student', 'taxi']
bag_of_words_matrix (init): 
[[0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]]
bag_of_words_matrix (final): 
[[0 0 0 1 0 0 0 0 0 1 0]
 [0 1 0 0 1 0 0 0 0 0 1]
 [1 0 1 0 0 0 0 0 1 0 0]
 [0 0 1 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 1 0 1 0 1 0]]


# Task 2: Calculate the IDF for the words “college” and “art”.

In [2]:
# Total number of phrases
total_phrases = len(phrases)

# Count how many phrases contain the word "college" and "art"
phrase_count_college = sum(["college" in phrase for phrase in phrases])
phrase_count_art = sum(["art" in phrase for phrase in phrases])

# Calculate IDF for "college" and "art"
idf_college = np.log(total_phrases / (1 + phrase_count_college))
idf_art = np.log(total_phrases / (1 + phrase_count_art))

# Print the IDF values
print(f'IDF for "college": {idf_college}')
print(f'IDF for "art": {idf_art}')


IDF for "college": 0.9162907318741551
IDF for "art": 0.5108256237659907
