<p style="font-family: Arial; font-size:3em;color:black;"> Lab Exercise 8</p>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import svm, datasets

In [2]:
# Import the built-in iris dataset to work with
iris = datasets.load_iris() # the dataset consists of 3 different types of irises' (Setosa, Versicolour, and Virginica) petal and sepal length
print("iris dataset",iris.data[:10,:])
X = iris.data[:, :2] # We only want to use the first two features (Sepal Length, Sepal Width)
y = iris.target # corresponding to 'setosa', 'versicolor', 'virginica
print("iris target",y[:10,])

iris dataset [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]
iris target [0 0 0 0 0 0 0 0 0 0]


In [ ]:
# Develop a linear Support Vector Machine to classify the irises
# Use GridSearchCV to optimize the model's hyperparameters (C, gamma, kernel)
# Compare the accuracies of the above two models

In [9]:
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=40)

linear_svm_model = SVC(kernel='linear')
linear_svm_model.fit(X_train,y_train)

linear_svm_accuaracy = accuracy_score(y_test, linear_svm_model.predict(X_test))
print('Linear SVM Accuracy: ', linear_svm_accuaracy)

Linear SVM Accuracy:  0.9


In [11]:
param_grid = {
    'C': [0.1,1,10,100],
    'kernel': ['linear','rbf','poly'],
    'gamma': ['scale','auto']
}
optimized_svm = SVC()
grid_search = GridSearchCV(estimator=optimized_svm, param_grid=param_grid, cv = 5)
grid_search.fit(X_train, y_train)

best_params = grid_search.best_params_
best_svm_model = grid_search.best_estimator_

best_svm_accuracy = accuracy_score(y_test, best_svm_model.predict(X_test))
print("Best SVM Accuracy: ", best_svm_accuracy)
print("Best Hyperparameters: ", best_params)


Best SVM Accuracy:  0.9333333333333333
Best Hyperparameters:  {'C': 0.1, 'gamma': 'scale', 'kernel': 'linear'}
