<p style="font-family: Arial; font-size:3em;color:black;"> Session 5 - Lab Exercise 9</p>

In [97]:
# For this example, we will use K-Means Clustering Project database from Kaggle (https://www.kaggle.com/faressayah/k-means-clustering-private-vs-public-universities)
# We actually have the labels for this data set, but we will NOT use them for the KMeans clustering algorithm, since that is an unsupervised learning algorithm.
# As we will shortly see, we have a data frame with 777 observations on 18 variables.

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.metrics import confusion_matrix

%matplotlib inline

In [98]:
df = pd.read_csv('College_Data',index_col=0)
df.columns

Index(['Private', 'Apps', 'Accept', 'Enroll', 'Top10perc', 'Top25perc',
       'F.Undergrad', 'P.Undergrad', 'Outstate', 'Room.Board', 'Books',
       'Personal', 'PhD', 'Terminal', 'S.F.Ratio', 'perc.alumni', 'Expend',
       'Grad.Rate'],
      dtype='object')

In [99]:
df['Grad.Rate']['Cazenovia College'] = 100

# Try removing various columns (features) from the dataset and examin if it improves/degrades your K-Means model performance, or it may have little impact.
# Report 10 cases where you removed one or more features and indicate how it impacted the model performance.

C:\Users\Syed\AppData\Local\Temp\ipykernel_14684\3450590736.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Grad.Rate']['Cazenovia College'] = 100


In [130]:
def Kmeans_performance(dataset):

    kmeans = KMeans(n_clusters=2, n_init=10)
    kmeans.fit(dataset.drop('Private',axis=1))   

    Cluster_predict=kmeans.predict(dataset.drop('Private',axis=1))
    dataset['Cluster_predict'] = Cluster_predict

    def convert_to_binary(cluster):  # converts labels for Private into binary values of 0 and 1
        if cluster=='Yes':
            return 1
        else:
            return 0

    dataset['Cluster_actual'] = dataset['Private'].apply(convert_to_binary)
    print(confusion_matrix(dataset['Cluster_actual'],kmeans.labels_))


In [138]:
print('Original Confusion Matrix:\n')
Kmeans_performance(df)

Original Confusion Matrix:

[[138  74]
 [531  34]]


In [102]:
cols_to_remove = ['Expend']
df_remove_cols = df.drop(columns=cols_to_remove)
Kmeans_performance(df_remove_cols)

[[121  91]
 [553  12]]


### Increase In False intances while True instances decreased

In [104]:
cols_to_remove = ['Outstate']
df_remove_cols = df.drop(columns=cols_to_remove)
Kmeans_performance(df_remove_cols)

[[138  74]
 [531  34]]


### No change

In [110]:
cols_to_remove = ['Enroll']
df_remove_cols = df.drop(columns=cols_to_remove)
Kmeans_performance(df_remove_cols)

[[123  89]
 [553  12]]


### Increase In False intances while True instances decreased

In [111]:
cols_to_remove = ['Accept']
df_remove_cols = df.drop(columns=cols_to_remove)
Kmeans_performance(df_remove_cols)

[[140  72]
 [534  31]]


### Increase In True intances while False instances decreased

In [140]:
cols_to_remove = ['Top10perc']
df_remove_cols = df.drop(columns=cols_to_remove)
Kmeans_performance(df_remove_cols)

[[138  74]
 [531  34]]


### No change

In [116]:
cols_to_remove = ['S.F.Ratio']
df_remove_cols = df.drop(columns=cols_to_remove)
Kmeans_performance(df_remove_cols)

[[138  74]
 [531  34]]


### No change


In [119]:
cols_to_remove = ['Room.Board']
df_remove_cols = df.drop(columns=cols_to_remove)
Kmeans_performance(df_remove_cols)

[[138  74]
 [531  34]]


### No change

In [120]:
cols_to_remove = ['Top10perc', 'Top25perc','F.Undergrad', 'P.Undergrad']
df_remove_multi_cols = df.drop(columns=cols_to_remove)
Kmeans_performance(df_remove_multi_cols)

[[189  23]
 [426 139]]


### Removing 4 cols ('Top10perc', 'Top25perc', 'F.Undergrad', 'P.Undergrad') from original df, increases the # of True instances and reduces some False instances

In [122]:
cols_to_remove = ['perc.alumni', 'Grad.Rate', 'PhD']
df_remove_multi_cols2 = df.drop(columns=cols_to_remove)
Kmeans_performance(df_remove_multi_cols2)

[[131  81]
 [553  12]]


### No change

In [141]:
cols_to_remove = ['PhD','Room.Board', 'Books','F.Undergrad']
df_remove_multi_cols3 = df.drop(columns=cols_to_remove)
Kmeans_performance(df_remove_multi_cols3)

[[ 23 189]
 [138 427]]


# TP/FP decreases drastically, meanwhile FP/FN increase substantially

'Private', 'Apps', 'Accept', 'Enroll', 'Top10perc', 'Top25perc',
       'F.Undergrad', 'P.Undergrad', 'Outstate', 'Room.Board', 'Books',
       'Personal', 'PhD', 'Terminal', 'S.F.Ratio', 'perc.alumni', 'Expend',
       'Grad.Rate'